/**
 * Clinical knowledge maps — curated reference data for trust scoring.
 *
 * Maps specialties to the equipment and procedures a facility SHOULD have
 * if it legitimately offers that specialty. This is the backbone of the
 * "Claims vs Evidence" dimension.
 *
 * Pure data — no I/O, no side effects.
 */

// ---------------------------------------------------------------------------
// Specialty requirements
// ---------------------------------------------------------------------------

export interface SpecialtyRequirement {
  /** Equipment items the specialty typically requires */
  equipment: string[];
  /** Procedures the specialty typically performs */
  procedures: string[];
  /** Minimum doctors needed to credibly offer this specialty */
  min_doctors?: number;
}

/**
 * At least one equipment OR procedure match per specialty is expected.
 * A specialty with ZERO matches is a critical red-flag.
 */
export const SPECIALTY_REQUIREMENTS: Record<string, SpecialtyRequirement> = {
  cardiology: {
    equipment: [
      'ECG',
      'Echo',
      'Echocardiography',
      'Defibrillator',
      'Holter Monitor',
      'Treadmill Test',
      'TMT',
      'Cardiac Monitor',
      'Cath Lab',
      'Pacemaker Programmer',
    ],
    procedures: [
      'Angiography',
      'Angioplasty',
      'Pacemaker Implantation',
      'Pacemaker',
      'CABG',
      'Cardiac Catheterization',
      'Stent Placement',
      'Electrophysiology Study',
      'Stress Test',
    ],
    min_doctors: 1,
  },
  radiology: {
    equipment: [
      'X-ray',
      'X-Ray',
      'CT Scanner',
      'CT Scan',
      'MRI',
      'MRI Scanner',
      'Ultrasound',
      'USG',
      'Mammography',
      'Fluoroscopy',
      'C-arm',
      'DEXA',
    ],
    procedures: [
      'CT Scan',
      'MRI Scan',
      'Mammography',
      'Ultrasound',
      'USG',
      'X-Ray',
      'Barium Study',
      'Fluoroscopy',
      'Interventional Radiology',
    ],
    min_doctors: 1,
  },
  orthopedics: {
    equipment: [
      'C-arm',
      'C-Arm',
      'Bone Densitometer',
      'DEXA',
      'Arthroscopy Set',
      'Traction Table',
      'Plaster Room',
      'Power Drill',
      'Image Intensifier',
    ],
    procedures: [
      'Joint Replacement',
      'Knee Replacement',
      'Hip Replacement',
      'Arthroscopy',
      'Fracture Fixation',
      'Spine Surgery',
      'Ligament Reconstruction',
      'Bone Grafting',
      'ORIF',
    ],
    min_doctors: 1,
  },
  pediatrics: {
    equipment: [
      'Nebulizer',
      'Infant Warmer',
      'Phototherapy Unit',
      'Pulse Oximeter',
      'Pediatric Ventilator',
      'Incubator',
      'Baby Weighing Scale',
      'NICU',
    ],
    procedures: [
      'Vaccination',
      'Immunization',
      'Neonatal Care',
      'Newborn Screening',
      'Growth Monitoring',
      'Pediatric Surgery',
    ],
    min_doctors: 1,
  },
  'general surgery': {
    equipment: [
      'Operation Theater',
      'Operation Theatre',
      'OT',
      'Anesthesia Machine',
      'Cautery Machine',
      'Electrocautery',
      'Autoclave',
      'Suction Machine',
      'Laparoscope',
      'Surgical Lights',
      'Boyle Apparatus',
    ],
    procedures: [
      'Laparoscopy',
      'Appendectomy',
      'Hernia Repair',
      'Cholecystectomy',
      'Circumcision',
      'Abscess Drainage',
      'Wound Debridement',
      'Hydrocele Surgery',
    ],
    min_doctors: 1,
  },
  surgery: {
    equipment: [
      'Operation Theater',
      'Operation Theatre',
      'OT',
      'Anesthesia Machine',
      'Cautery Machine',
      'Electrocautery',
      'Autoclave',
      'Suction Machine',
      'Laparoscope',
    ],
    procedures: [
      'Laparoscopy',
      'Appendectomy',
      'Hernia Repair',
      'Cholecystectomy',
      'General Surgery',
    ],
    min_doctors: 1,
  },
  oncology: {
    equipment: [
      'Linear Accelerator',
      'LINAC',
      'Cobalt-60',
      'Brachytherapy',
      'PET-CT',
      'PET Scanner',
      'Chemotherapy Chair',
      'Bone Marrow Biopsy Set',
    ],
    procedures: [
      'Chemotherapy',
      'Radiation Therapy',
      'Radiotherapy',
      'Tumor Excision',
      'Bone Marrow Transplant',
      'Brachytherapy',
      'Immunotherapy',
    ],
    min_doctors: 1,
  },
  neurology: {
    equipment: [
      'EEG',
      'EMG',
      'NCV',
      'CT Scanner',
      'MRI',
      'Nerve Conduction',
      'Doppler Ultrasound',
    ],
    procedures: [
      'EEG',
      'EMG',
      'Nerve Conduction Study',
      'Lumbar Puncture',
      'Stroke Management',
      'Epilepsy Management',
      'Botox Injection',
    ],
    min_doctors: 1,
  },
  neurosurgery: {
    equipment: [
      'Operating Microscope',
      'Neuronavigation',
      'CT Scanner',
      'MRI',
      'Craniotomy Set',
      'High-Speed Drill',
      'C-arm',
    ],
    procedures: [
      'Craniotomy',
      'Spine Surgery',
      'VP Shunt',
      'Brain Tumor Surgery',
      'Disc Surgery',
      'Laminectomy',
    ],
    min_doctors: 1,
  },
  nephrology: {
    equipment: [
      'Dialysis Machine',
      'Hemodialysis',
      'Peritoneal Dialysis',
      'RO Plant',
      'Water Treatment',
      'Fistula Needle',
    ],
    procedures: [
      'Hemodialysis',
      'Peritoneal Dialysis',
      'Kidney Biopsy',
      'Renal Transplant',
      'AV Fistula',
      'CAPD',
    ],
    min_doctors: 1,
  },
  gastroenterology: {
    equipment: [
      'Endoscope',
      'Colonoscope',
      'Upper GI Endoscope',
      'ERCP',
      'Ultrasound',
      'Fibroscan',
    ],
    procedures: [
      'Endoscopy',
      'Colonoscopy',
      'ERCP',
      'Polypectomy',
      'Liver Biopsy',
      'Variceal Banding',
      'PEG Insertion',
    ],
    min_doctors: 1,
  },
  dermatology: {
    equipment: [
      'Dermatoscope',
      'Cryotherapy',
      'Electrocautery',
      'Laser',
      'Wood Lamp',
      'UV Phototherapy',
    ],
    procedures: [
      'Skin Biopsy',
      'Cryotherapy',
      'Laser Treatment',
      'Excision',
      'Chemical Peel',
      'Phototherapy',
    ],
    min_doctors: 1,
  },
  ent: {
    equipment: [
      'Otoscope',
      'Audiometer',
      'Endoscope',
      'Nasal Endoscope',
      'Microscope',
      'Tympanometer',
      'Hearing Aid',
    ],
    procedures: [
      'Tonsillectomy',
      'Adenoidectomy',
      'Septoplasty',
      'Myringotomy',
      'FESS',
      'Mastoidectomy',
      'Hearing Test',
      'Audiometry',
    ],
    min_doctors: 1,
  },
  ophthalmology: {
    equipment: [
      'Slit Lamp',
      'Tonometer',
      'Auto Refractometer',
      'Fundus Camera',
      'OCT',
      'Phaco Machine',
      'Keratometer',
      'A-scan',
      'B-scan',
      'Perimeter',
      'YAG Laser',
    ],
    procedures: [
      'Cataract Surgery',
      'Phacoemulsification',
      'Glaucoma Surgery',
      'Retinal Laser',
      'LASIK',
      'Pterygium Excision',
      'Squint Surgery',
      'Vitrectomy',
    ],
    min_doctors: 1,
  },
  gynecology: {
    equipment: [
      'Ultrasound',
      'USG',
      'Colposcope',
      'Fetal Monitor',
      'CTG Machine',
      'Hysteroscope',
      'Laparoscope',
      'Infant Warmer',
    ],
    procedures: [
      'Cesarean Section',
      'C-Section',
      'Hysterectomy',
      'D&C',
      'Laparoscopic Surgery',
      'IVF',
      'Tubal Ligation',
      'Normal Delivery',
      'Hysteroscopy',
    ],
    min_doctors: 1,
  },
  obstetrics: {
    equipment: [
      'Ultrasound',
      'USG',
      'Fetal Monitor',
      'CTG Machine',
      'Infant Warmer',
      'Delivery Table',
      'Phototherapy Unit',
      'Incubator',
    ],
    procedures: [
      'Normal Delivery',
      'Cesarean Section',
      'C-Section',
      'Episiotomy',
      'Vacuum Extraction',
      'Antenatal Care',
      'Postnatal Care',
    ],
    min_doctors: 1,
  },
  urology: {
    equipment: [
      'Cystoscope',
      'Urodynamic Machine',
      'Lithotripter',
      'ESWL',
      'Ultrasound',
      'Laser',
    ],
    procedures: [
      'Cystoscopy',
      'TURP',
      'Lithotripsy',
      'ESWL',
      'Ureteral Stent',
      'Nephrectomy',
      'Prostate Biopsy',
      'Circumcision',
    ],
    min_doctors: 1,
  },
  psychiatry: {
    equipment: ['ECT Machine', 'EEG', 'Counseling Room', 'Seclusion Room'],
    procedures: [
      'ECT',
      'Counseling',
      'Psychotherapy',
      'CBT',
      'De-addiction',
      'Rehabilitation',
    ],
    min_doctors: 1,
  },
  pulmonology: {
    equipment: [
      'Spirometer',
      'Bronchoscope',
      'Ventilator',
      'CPAP',
      'BiPAP',
      'Nebulizer',
      'Pulse Oximeter',
      'ABG Machine',
      'Chest Drainage Set',
    ],
    procedures: [
      'Bronchoscopy',
      'Spirometry',
      'Thoracentesis',
      'Chest Tube Insertion',
      'Pulmonary Function Test',
      'PFT',
      'Sleep Study',
    ],
    min_doctors: 1,
  },
  endocrinology: {
    equipment: [
      'Glucometer',
      'HbA1c Analyzer',
      'Thyroid Function Lab',
      'Insulin Pump',
      'Bone Densitometer',
      'DEXA',
    ],
    procedures: [
      'Thyroid Biopsy',
      'FNAC Thyroid',
      'Insulin Pump Therapy',
      'Diabetes Management',
      'Hormonal Assay',
    ],
    min_doctors: 1,
  },
  'critical care': {
    equipment: [
      'Ventilator',
      'ICU Bed',
      'Cardiac Monitor',
      'Multi-Para Monitor',
      'Infusion Pump',
      'Syringe Pump',
      'Defibrillator',
      'ABG Machine',
      'Central Line Kit',
      'CPAP',
      'BiPAP',
    ],
    procedures: [
      'Mechanical Ventilation',
      'Central Line Insertion',
      'Arterial Line',
      'Intubation',
      'Tracheostomy',
      'Chest Tube',
    ],
    min_doctors: 2,
  },
  icu: {
    equipment: [
      'Ventilator',
      'ICU Bed',
      'Cardiac Monitor',
      'Multi-Para Monitor',
      'Infusion Pump',
      'Syringe Pump',
      'Defibrillator',
      'ABG Machine',
    ],
    procedures: [
      'Mechanical Ventilation',
      'Central Line Insertion',
      'Intubation',
      'Tracheostomy',
    ],
    min_doctors: 2,
  },
  'emergency medicine': {
    equipment: [
      'Defibrillator',
      'Ventilator',
      'Cardiac Monitor',
      'Pulse Oximeter',
      'Suction Machine',
      'Ambu Bag',
      'Crash Cart',
      'Spine Board',
      'Nebulizer',
    ],
    procedures: [
      'CPR',
      'Intubation',
      'Fracture Splinting',
      'Wound Suturing',
      'Poison Management',
      'Trauma Care',
      'Emergency Resuscitation',
    ],
    min_doctors: 1,
  },
  dental: {
    equipment: [
      'Dental Chair',
      'Dental X-ray',
      'RVG',
      'OPG',
      'Autoclave',
      'Scaler',
      'Compressor',
      'Light Cure',
    ],
    procedures: [
      'Root Canal',
      'RCT',
      'Extraction',
      'Scaling',
      'Filling',
      'Crown',
      'Bridge',
      'Implant',
      'Orthodontics',
      'Braces',
    ],
    min_doctors: 1,
  },
  physiotherapy: {
    equipment: [
      'Ultrasound Therapy',
      'TENS',
      'IFT',
      'SWD',
      'Traction Unit',
      'Exercise Bike',
      'Parallel Bars',
      'Wax Bath',
      'Laser Therapy',
    ],
    procedures: [
      'Physiotherapy',
      'Rehabilitation',
      'Post-operative Rehab',
      'Sports Injury Rehab',
      'Stroke Rehab',
      'Manual Therapy',
    ],
    min_doctors: 1,
  },
  pathology: {
    equipment: [
      'Microscope',
      'Hematology Analyzer',
      'Biochemistry Analyzer',
      'Centrifuge',
      'ELISA Reader',
      'Blood Bank Refrigerator',
      'Culture Incubator',
      'ABG Machine',
    ],
    procedures: [
      'Blood Test',
      'CBC',
      'Biopsy',
      'FNAC',
      'Histopathology',
      'Culture Sensitivity',
      'Blood Grouping',
      'Cross Matching',
    ],
    min_doctors: 1,
  },
  laboratory: {
    equipment: [
      'Microscope',
      'Hematology Analyzer',
      'Biochemistry Analyzer',
      'Centrifuge',
      'ELISA Reader',
    ],
    procedures: [
      'Blood Test',
      'CBC',
      'Urine Analysis',
      'Culture Sensitivity',
      'Serology',
    ],
    min_doctors: 1,
  },
  'plastic surgery': {
    equipment: [
      'Operation Theater',
      'Microsurgical Instruments',
      'Dermatome',
      'Laser',
      'Liposuction Machine',
    ],
    procedures: [
      'Skin Grafting',
      'Flap Surgery',
      'Rhinoplasty',
      'Cleft Lip Repair',
      'Burn Management',
      'Liposuction',
      'Hair Transplant',
    ],
    min_doctors: 1,
  },
  'general medicine': {
    equipment: [
      'Stethoscope',
      'BP Apparatus',
      'Thermometer',
      'Pulse Oximeter',
      'Glucometer',
      'ECG',
      'Nebulizer',
    ],
    procedures: [
      'General Consultation',
      'Health Checkup',
      'Vaccination',
      'Chronic Disease Management',
    ],
    min_doctors: 1,
  },
  anesthesiology: {
    equipment: [
      'Anesthesia Machine',
      'Boyle Apparatus',
      'Ventilator',
      'Laryngoscope',
      'Pulse Oximeter',
      'Capnograph',
      'Infusion Pump',
      'Syringe Pump',
    ],
    procedures: [
      'General Anesthesia',
      'Spinal Anesthesia',
      'Epidural',
      'Regional Block',
      'Pain Management',
      'Sedation',
    ],
    min_doctors: 1,
  },
};

// ---------------------------------------------------------------------------
// Synonyms — map variant names to canonical keys in SPECIALTY_REQUIREMENTS
// ---------------------------------------------------------------------------

export const SPECIALTY_SYNONYMS: Record<string, string> = {
  // Cardiology
  cardiac: 'cardiology',
  'cardiac surgery': 'cardiology',
  'cardiac surgeon': 'cardiology',
  'cardiac sciences': 'cardiology',
  'cardiac science': 'cardiology',
  'cardiac care': 'cardiology',
  'cardiac diseases': 'cardiology',
  'cardiac electrophysiology': 'cardiology',
  'cardiac rehabilitation': 'cardiology',
  'cardio thoracic surgery': 'cardiology',
  'cardiothoracic surgery': 'cardiology',
  'cardiothoracic': 'cardiology',
  'cardiovascular': 'cardiology',
  'cardiovascular surgery': 'cardiology',
  'cardiovascular thoracic surgery': 'cardiology',
  'ctvs': 'cardiology',
  'cvts': 'cardiology',
  'interventional cardiology': 'cardiology',
  'interventional cardiologist': 'cardiology',
  'non-interventional cardiology': 'cardiology',
  'non-invasive cardiology': 'cardiology',
  'preventive cardiology': 'cardiology',
  'sports cardiology': 'cardiology',
  'transradial cardiology': 'cardiology',
  'heart & lung transplant': 'cardiology',
  'electrophysiology': 'cardiology',
  'cardiologist': 'cardiology',
  'cardio oncology': 'cardiology',

  // General surgery
  surgical: 'general surgery',
  'gen surgery': 'general surgery',
  'minimal invasive surgery': 'general surgery',
  'minimally invasive surgery': 'general surgery',
  'laparoscopic surgery': 'general surgery',
  'laparoscopy': 'general surgery',
  'bariatric surgery': 'general surgery',
  'bariatrics': 'general surgery',
  'metabolic surgery': 'general surgery',
  'hernia surgery': 'general surgery',
  'vascular surgery': 'general surgery',
  'transplant surgery': 'general surgery',
  'multi-organ transplant': 'general surgery',
  'robotic surgery': 'general surgery',
  'acute care surgery': 'general surgery',
  'trauma surgery': 'general surgery',
  'colorectal surgery': 'general surgery',
  'breast surgery': 'general surgery',
  'endocrine surgery': 'general surgery',
  'liver transplant': 'general surgery',
  'hepatobiliary surgery': 'general surgery',
  'hepato-pancreato-biliary': 'general surgery',
  'hepato-biliary-pancreatic': 'general surgery',
  'hpb & gi surgery': 'general surgery',
  'gi surgery': 'general surgery',
  'gastrointestinal surgery': 'general surgery',
  'surgical gastroenterology': 'general surgery',
  'laparoscopic surgeon': 'general surgery',
  'general & laparoscopic surgery': 'general surgery',
  'polytrauma': 'general surgery',

  // Orthopedics
  orthopaedics: 'orthopedics',
  ortho: 'orthopedics',
  'orthopedic surgery': 'orthopedics',
  'orthopaedic surgery': 'orthopedics',
  'bone & joint': 'orthopedics',
  'bone and joint': 'orthopedics',
  'joint replacement': 'orthopedics',
  'joint replacement surgery': 'orthopedics',
  'joint replacement surgeries': 'orthopedics',
  'knee replacement specialist': 'orthopedics',
  'hip replacement specialist': 'orthopedics',
  'hip replacement surgery': 'orthopedics',
  'hip & knee reconstructive surgeon': 'orthopedics',
  'arthroscopic surgery': 'orthopedics',
  'arthroscopic surgeries': 'orthopedics',
  'arthroscopy': 'orthopedics',
  'arthroscopy & sports medicine': 'orthopedics',
  'spine surgery': 'orthopedics',
  'sports medicine': 'orthopedics',
  'sports injury management': 'orthopedics',
  'orthopedic trauma specialist': 'orthopedics',
  'osteoarthritis specialist': 'orthopedics',
  'trauma & orthopaedic': 'orthopedics',
  'traumatology': 'orthopedics',
  'orthopedics & joint replacement': 'orthopedics',
  'orthopaedics & joint replacement': 'orthopedics',
  'orthopedics & traumatology': 'orthopedics',
  'orthopaedics and trauma': 'orthopedics',
  'robotic joint replacement surgery': 'orthopedics',
  'knee surgery': 'orthopedics',
  'shoulder & elbow orthopedic surgery': 'orthopedics',

  // ENT
  otorhinolaryngology: 'ent',
  otolaryngology: 'ent',
  'ear nose throat': 'ent',
  'ear nose throat surgery': 'ent',
  'ear, nose & throat': 'ent',
  'ear-nose-throat (ent) specialist': 'ent',
  'ent (otolaryngology)': 'ent',
  'ent / otorhinolaryngology': 'ent',
  'ent/ otorhinolaryngologist': 'ent',
  'ent and head & neck surgery': 'ent',
  'ent, head & neck surgery': 'ent',
  'ent and skull base surgery': 'ent',
  'head & neck surgery': 'ent',
  'head and neck surgery': 'ent',
  'laryngology': 'ent',
  'rhinology': 'ent',
  'pediatric ent': 'ent',

  // Ophthalmology
  eye: 'ophthalmology',
  'eye care': 'ophthalmology',
  'eye hospital': 'ophthalmology',
  'children eye care': 'ophthalmology',
  'pediatric ophthalmology': 'ophthalmology',
  'pediatric opthalmology': 'ophthalmology',
  'paediatric ophthalmology': 'ophthalmology',
  'community ophthalmology': 'ophthalmology',
  'neuro ophthalmology': 'ophthalmology',
  oculoplasty: 'ophthalmology',
  'vitreoretinal': 'ophthalmology',
  'vitreo-retinal surgery': 'ophthalmology',
  'retinal diseases': 'ophthalmology',
  'retinology': 'ophthalmology',
  'medical retina': 'ophthalmology',
  'glaucoma': 'ophthalmology',
  'cataract': 'ophthalmology',
  'lasik': 'ophthalmology',
  'lasik surgery': 'ophthalmology',
  'lasik (refractive surgery)': 'ophthalmology',
  'refractive surgeries': 'ophthalmology',
  'corneal disease': 'ophthalmology',
  'squint': 'ophthalmology',
  'squint & orthoptics': 'ophthalmology',
  'squint eye treatment': 'ophthalmology',
  'strabismus': 'ophthalmology',
  'binocular vision & squint': 'ophthalmology',
  'keratoconus': 'ophthalmology',
  'diabetic retinopathy': 'ophthalmology',
  'contoura lasik': 'ophthalmology',
  'contoura vision': 'ophthalmology',
  'mics & cataract': 'ophthalmology',
  'icl surgery': 'ophthalmology',
  'prk surgery': 'ophthalmology',

  // Gynecology / Obstetrics
  'obs & gyn': 'gynecology',
  'obs and gyn': 'gynecology',
  'obstetrics & gynecology': 'gynecology',
  'obstetrics and gynecology': 'gynecology',
  'obstetrics & gynaecology': 'gynecology',
  'obstetrics and gynaecology': 'gynecology',
  'obstetrics&gynaecology': 'gynecology',
  'obsterics & gynaecology': 'gynecology',
  'ob-gyn': 'gynecology',
  'obgyn': 'gynecology',
  'obg': 'gynecology',
  'o&g': 'gynecology',
  'gynaecology': 'gynecology',
  'gynaecology & obstetrics': 'gynecology',
  'gynecology and obstetrics': 'gynecology',
  'gynae oncology': 'gynecology',
  'gynaecologic oncology': 'gynecology',
  'gynaeoncology': 'gynecology',
  'gynecological cancer': 'gynecology',
  'gynecological oncology': 'gynecology',
  'gynecological surgery': 'gynecology',
  'infertility': 'gynecology',
  'infertility clinic': 'gynecology',
  'infertility / ivf': 'gynecology',
  'infertility & impotency': 'gynecology',
  'ivf': 'gynecology',
  'ivf treatment': 'gynecology',
  'iui': 'gynecology',
  'iui treatment': 'gynecology',
  'icsi': 'gynecology',
  'icsi treatment': 'gynecology',
  'fertility': 'gynecology',
  'fertility preservation': 'gynecology',
  'reproductive surgery': 'gynecology',
  "women's health and fertility": 'gynecology',
  'male infertility': 'gynecology',
  'andrology': 'gynecology',
  'maternity': 'obstetrics',
  'obstetrics?': 'obstetrics',
  'obstetrics and maternity care': 'obstetrics',
  'neonatal-perinatal': 'obstetrics',
  'fetal medicine and radiology': 'obstetrics',

  // Pediatrics
  paediatrics: 'pediatrics',
  'child care': 'pediatrics',
  neonatology: 'pediatrics',
  'neonatal care': 'pediatrics',
  'nicu/ picu/ neonatology': 'pediatrics',
  'paediatrics & neonatology': 'pediatrics',
  'paediatrics & neonatal care': 'pediatrics',
  'pediatrics & neonatology': 'pediatrics',
  'peadiatrics & neonatology': 'pediatrics',
  'developmental paediatrics': 'pediatrics',
  'pediatric cardiology': 'pediatrics',
  'paediatric cardiology': 'pediatrics',
  'pediatric surgery': 'pediatrics',
  'paediatric surgery': 'pediatrics',
  'pediatric neurology': 'pediatrics',
  'paediatric neurology': 'pediatrics',
  'pediatric orthopedics': 'pediatrics',
  'pediatric dermatology': 'pediatrics',
  'pediatric gastroenterology': 'pediatrics',
  'paediatric gastroenterology': 'pediatrics',
  'paediatric nephrology': 'pediatrics',
  'pediatric nephrology': 'pediatrics',
  'paediatric pulmonology': 'pediatrics',
  'pediatric pulmonology': 'pediatrics',
  'new born screening': 'pediatrics',

  // Nephrology
  renal: 'nephrology',
  kidney: 'nephrology',
  'renal sciences': 'nephrology',
  'nephrology & dialysis': 'nephrology',
  'nephrology and renal science': 'nephrology',
  dialysis: 'nephrology',
  'nephro surgery': 'nephrology',
  'kidney transplant': 'nephrology',
  'kidney transplant surgery': 'nephrology',
  'kidney stone surgery': 'nephrology',

  // Pulmonology
  'respiratory medicine': 'pulmonology',
  'chest medicine': 'pulmonology',
  'chest physician': 'pulmonology',
  'pulmonary medicine': 'pulmonology',
  'tb & chest': 'pulmonology',
  'tuberculosis tb and chest': 'pulmonology',
  'tuberculosis and respiratory medicine/pulmonary medicine': 'pulmonology',
  'respiratory diseases management': 'pulmonology',
  'pulmonologist': 'pulmonology',
  'pulmonology and respiratory medicine': 'pulmonology',

  // Gastroenterology
  gastro: 'gastroenterology',
  digestive: 'gastroenterology',
  'gastro sciences': 'gastroenterology',
  'gastroscience': 'gastroenterology',
  'gastroenterologist': 'gastroenterology',
  'medical gastroenterology': 'gastroenterology',
  'gastroenterology & hepatology': 'gastroenterology',
  'gastroenterology & hepatobiliary surgery': 'gastroenterology',
  hepatology: 'gastroenterology',
  'hepatology and liver disease management': 'gastroenterology',
  'gi oncology': 'gastroenterology',
  'gi cancer': 'gastroenterology',
  'endoscopy': 'gastroenterology',
  'endoscopy & laproscopy': 'gastroenterology',

  // Dermatology
  skin: 'dermatology',
  'skin & vd': 'dermatology',
  cosmetology: 'dermatology',
  'cosmetology & dermatology': 'dermatology',
  'dermato surgery': 'dermatology',
  'dermatosurgery': 'dermatology',
  'aesthetic dermatology': 'dermatology',
  'geriatric dermatology': 'dermatology',
  trichology: 'dermatology',
  venerology: 'dermatology',

  // Psychiatry
  'mental health': 'psychiatry',
  'behavioral health': 'psychiatry',
  'clinical psychology': 'psychiatry',
  psychology: 'psychiatry',
  psychotherapy: 'psychiatry',
  'counseling/clinical psychology': 'psychiatry',
  neuropsychiatry: 'psychiatry',
  'sexologists': 'psychiatry',
  'sexual medicine': 'psychiatry',

  // Endocrinology
  diabetes: 'endocrinology',
  diabetology: 'endocrinology',
  'diabetes management': 'endocrinology',
  'diabetic foot surgery': 'endocrinology',

  // ICU / Critical care
  'intensive care': 'critical care',
  'critical care medicine': 'critical care',
  'critaical care & emergency': 'critical care',
  'icu & critical care': 'critical care',
  'intensive care physician and critical care': 'critical care',
  'i.c.u.': 'critical care',
  'intensivist & anaesthesiologist': 'critical care',

  // Emergency
  emergency: 'emergency medicine',
  casualty: 'emergency medicine',
  trauma: 'emergency medicine',
  'accident & emergency': 'emergency medicine',
  'accident & trauma': 'emergency medicine',
  'emergency trauma care': 'emergency medicine',
  'trauma care': 'emergency medicine',

  // Laboratory
  lab: 'laboratory',
  'clinical laboratory': 'laboratory',
  'diagnostic lab': 'laboratory',
  'laboratory sciences': 'laboratory',
  'diagnostic testing': 'laboratory',
  'pathology laboratory': 'laboratory',

  // Physiotherapy
  physio: 'physiotherapy',
  physiotherapist: 'physiotherapy',
  'physical therapy': 'physiotherapy',
  rehabilitation: 'physiotherapy',
  'physical medicine': 'physiotherapy',
  'physical medicine and rehabilitation': 'physiotherapy',
  'occupational therapy': 'physiotherapy',
  'physiothearpy': 'physiotherapy',
  'advanced physiotherapy': 'physiotherapy',

  // Dental
  dentistry: 'dental',
  'oral surgery': 'dental',
  'general dentistry': 'dental',
  'dental science': 'dental',
  'dental medicine': 'dental',
  'dental implantology': 'dental',
  'dental implants': 'dental',
  'implant dentistry': 'dental',
  'implantologist': 'dental',
  'dentistry & maxillofacial surgery': 'dental',
  'cosmetic dentistry': 'dental',
  'cosmetics dentistry': 'dental',
  'aestheticsdentistry': 'dental',
  'aesthetic dentistry': 'dental',
  'pediatric dentistry': 'dental',
  'paediatric dentistry': 'dental',
  'kids dentistry': 'dental',
  'preventive dentistry': 'dental',
  'sedation dentistry': 'dental',
  'laser dentistry': 'dental',
  'conservative dentistry': 'dental',
  'general / community dentistry': 'dental',
  'specialty & cosmetic dentistry': 'dental',
  'public health dentistry': 'dental',
  'advanced dentistry': 'dental',
  'endodontics': 'dental',
  'endodontist': 'dental',
  'endodontics and conservative dentistry': 'dental',
  orthodontics: 'dental',
  'orthodontics and clear aligners': 'dental',
  orthodontist: 'dental',
  pedodontics: 'dental',
  'pedodontics dentistry': 'dental',
  pedodontist: 'dental',
  'paedodontist': 'dental',
  periodontics: 'dental',
  periodontist: 'dental',
  periodontology: 'dental',
  'periodontology and implantology': 'dental',
  'periondontics': 'dental',
  prosthodontics: 'dental',
  'prosthodontics and crown & bridge': 'dental',
  prosthodontist: 'dental',
  'prosthodontoics': 'dental',
  'oral & maxillo-facial radiology': 'dental',
  'oral and maxillofacial surgery': 'dental',
  'oral and maxillofacialsurgery': 'dental',
  'oral medicine': 'dental',
  'oral medicine & radiology': 'dental',
  'oral medicine and radiology': 'dental',
  'oral pathology': 'dental',
  'oral medicine radiology and pathology': 'dental',
  'maxillo facial surgery': 'dental',
  'maxillofacial surgery': 'dental',
  'faciomaxillary': 'dental',
  'dentofacial orthopedics': 'dental',
  'neuromuscular orthodontics': 'dental',
  'orthognathic surgery': 'dental',

  // Neurology
  neuro: 'neurology',
  'neuro sciences': 'neurology',
  'neuro medicine': 'neurology',
  'neurosciences': 'neurology',
  'neuroscience': 'neurology',
  'neurosciences & spinal disorders': 'neurology',
  'neuro electro-physiology': 'neurology',

  // Neurosurgery — keep separate from neurology
  'brain tumor surgery': 'neurosurgery',
  'brain spine surgery': 'neurosurgery',

  // Oncology
  cancer: 'oncology',
  'cancer care': 'oncology',
  'cancer surgery': 'oncology',
  'radiation oncology': 'oncology',
  'medical oncology': 'oncology',
  'surgical oncology': 'oncology',
  'surgical oncologist': 'oncology',
  'oncologist/cancer specialist': 'oncology',
  'onco surgery': 'oncology',
  'onco care': 'oncology',
  'head & neck oncology': 'oncology',
  'head and neck cancer': 'oncology',
  'head and neck oncology': 'oncology',
  'breast oncology and reconstruction': 'oncology',
  'hemato oncology': 'oncology',
  'hemato oncology & bmt': 'oncology',
  'hemato-oncology': 'oncology',
  'hematology': 'oncology',
  'hematology & hemato oncology': 'oncology',
  'haematology': 'oncology',
  'haematology & haemato oncology': 'oncology',
  'stem cell transplant': 'oncology',
  'stem cell transplantation': 'oncology',
  'bone marrow transplant': 'oncology',
  'thoracic cancer': 'oncology',
  'uro-oncology': 'oncology',
  'urology oncology': 'oncology',
  'gi & uro-oncology': 'oncology',
  'gastrointestinal oncology': 'oncology',
  'paediatric hemato oncology & bmt': 'oncology',

  // General medicine
  medicine: 'general medicine',
  'internal medicine': 'general medicine',
  'family medicine': 'general medicine',
  'general physician': 'general medicine',
  'general internal medicine': 'general medicine',
  physician: 'general medicine',
  'geriatric care': 'general medicine',
  immunology: 'general medicine',
  'allergy and immunology': 'general medicine',
  'infectious diseases': 'general medicine',
  'rheumatology': 'general medicine',
  'transfusion medicine': 'general medicine',
  'nuclear medicine': 'general medicine',

  // Urology
  'uro surgery': 'urology',
  'urosurgery': 'urology',
  'endourology': 'urology',
  'robotic urology': 'urology',
  'urology & renal transplant surgery': 'urology',
  'urology and andrology': 'urology',
  'prostate surgery': 'urology',

  // Plastic surgery
  cosmetic: 'plastic surgery',
  'cosmetic surgery': 'plastic surgery',
  'cosmetic and plastic surgery': 'plastic surgery',
  'reconstructive surgery': 'plastic surgery',
  'plastic & cosmetic surgery': 'plastic surgery',
  'plastic & reconstructive surgery': 'plastic surgery',
  'plastic surgery & cosmetic surgery': 'plastic surgery',
  'plastic surgeon': 'plastic surgery',
  'burns management': 'plastic surgery',
  'burn and trauma plastic surgery': 'plastic surgery',
  'burns and plastic surgery': 'plastic surgery',
  'cleft and craniofacial surgery': 'plastic surgery',
  'hair transplantation': 'plastic surgery',
  'micro vascular surgery': 'plastic surgery',

  // Anesthesiology
  anaesthesia: 'anesthesiology',
  anaesthesiology: 'anesthesiology',
  anesthesia: 'anesthesiology',
  'anaesthesia & critical care': 'anesthesiology',
  'anaesthesia & intensive care': 'anesthesiology',
  'anaesthesiology & critical care': 'anesthesiology',
  'anesthesiology department': 'anesthesiology',
  'pain management': 'anesthesiology',
  'interventional pain management': 'anesthesiology',

  // Pathology
  histopathology: 'pathology',
  'clinical pathology': 'pathology',
  'histopathology & cytology': 'pathology',
  'cytology': 'pathology',
  'cytology & histopathology': 'pathology',
  'cytopathology': 'pathology',
  'surgical pathology': 'pathology',
  'molecular pathology': 'pathology',
  'hematopathology': 'pathology',
  'immunopathology': 'pathology',
  microbiology: 'pathology',
  'micro biology': 'pathology',
  biochemistry: 'pathology',
  serology: 'pathology',

  // Radiology
  imaging: 'radiology',
  'diagnostic imaging': 'radiology',
  'interventional radiology': 'radiology',
  'radio diagnostics': 'radiology',
  'radiology/ultrasonology': 'radiology',
  sonography: 'radiology',
  '3d-4d sonography and ultrasound': 'radiology',
  '24 hrs digital x ray': 'radiology',
  '24 hrs diagnostics': 'radiology',
  'color doppler': 'radiology',
};

// ---------------------------------------------------------------------------
// Keyword-based fallback rules for normalizing specialty names that don't
// appear in the explicit synonyms map. Checked in order — first match wins.
// This handles the long tail of camelCase variants and compound names.
// ---------------------------------------------------------------------------

export const SPECIALTY_KEYWORD_RULES: Array<{ keywords: string[]; canonical: string }> = [
  { keywords: ['cardiothoracic'], canonical: 'cardiology' },
  { keywords: ['cardiovascular'], canonical: 'cardiology' },
  { keywords: ['cardiac'], canonical: 'cardiology' },
  { keywords: ['cardiology'], canonical: 'cardiology' },
  { keywords: ['cardiologist'], canonical: 'cardiology' },
  { keywords: ['neurosurgery'], canonical: 'neurosurgery' },
  { keywords: ['neurosurgeon'], canonical: 'neurosurgery' },
  { keywords: ['skull', 'base'], canonical: 'neurosurgery' },
  { keywords: ['brain', 'surgery'], canonical: 'neurosurgery' },
  { keywords: ['spine', 'surgery'], canonical: 'neurosurgery' },
  { keywords: ['neurology'], canonical: 'neurology' },
  { keywords: ['neurologist'], canonical: 'neurology' },
  { keywords: ['neuroscience'], canonical: 'neurology' },
  { keywords: ['nephrology'], canonical: 'nephrology' },
  { keywords: ['nephrologist'], canonical: 'nephrology' },
  { keywords: ['renal'], canonical: 'nephrology' },
  { keywords: ['kidney'], canonical: 'nephrology' },
  { keywords: ['dialysis'], canonical: 'nephrology' },
  { keywords: ['oncology'], canonical: 'oncology' },
  { keywords: ['oncologist'], canonical: 'oncology' },
  { keywords: ['onco'], canonical: 'oncology' },
  { keywords: ['cancer'], canonical: 'oncology' },
  { keywords: ['hematology'], canonical: 'oncology' },
  { keywords: ['haematology'], canonical: 'oncology' },
  { keywords: ['hemato'], canonical: 'oncology' },
  { keywords: ['bone', 'marrow'], canonical: 'oncology' },
  { keywords: ['stem', 'cell'], canonical: 'oncology' },
  { keywords: ['radiation'], canonical: 'oncology' },
  { keywords: ['radiotherapy'], canonical: 'oncology' },
  { keywords: ['ophthalmology'], canonical: 'ophthalmology' },
  { keywords: ['ophthalmologist'], canonical: 'ophthalmology' },
  { keywords: ['oculoplast'], canonical: 'ophthalmology' },
  { keywords: ['vitreoretinal'], canonical: 'ophthalmology' },
  { keywords: ['retina'], canonical: 'ophthalmology' },
  { keywords: ['glaucoma'], canonical: 'ophthalmology' },
  { keywords: ['cataract'], canonical: 'ophthalmology' },
  { keywords: ['lasik'], canonical: 'ophthalmology' },
  { keywords: ['refractive'], canonical: 'ophthalmology' },
  { keywords: ['cornea'], canonical: 'ophthalmology' },
  { keywords: ['squint'], canonical: 'ophthalmology' },
  { keywords: ['strabismus'], canonical: 'ophthalmology' },
  { keywords: ['keratoconus'], canonical: 'ophthalmology' },
  { keywords: ['eye', 'care'], canonical: 'ophthalmology' },
  { keywords: ['gynecolog'], canonical: 'gynecology' },
  { keywords: ['gynaecolog'], canonical: 'gynecology' },
  { keywords: ['obstetric'], canonical: 'obstetrics' },
  { keywords: ['infertility'], canonical: 'gynecology' },
  { keywords: ['fertility'], canonical: 'gynecology' },
  { keywords: ['ivf'], canonical: 'gynecology' },
  { keywords: ['icsi'], canonical: 'gynecology' },
  { keywords: ['iui'], canonical: 'gynecology' },
  { keywords: ['reproductive'], canonical: 'gynecology' },
  { keywords: ['andrology'], canonical: 'gynecology' },
  { keywords: ['paediatric'], canonical: 'pediatrics' },
  { keywords: ['pediatric'], canonical: 'pediatrics' },
  { keywords: ['neonatolog'], canonical: 'pediatrics' },
  { keywords: ['orthopaedic'], canonical: 'orthopedics' },
  { keywords: ['orthopedic'], canonical: 'orthopedics' },
  { keywords: ['arthroscop'], canonical: 'orthopedics' },
  { keywords: ['joint', 'replacement'], canonical: 'orthopedics' },
  { keywords: ['sports', 'medicine'], canonical: 'orthopedics' },
  { keywords: ['gastroenterolog'], canonical: 'gastroenterology' },
  { keywords: ['hepatolog'], canonical: 'gastroenterology' },
  { keywords: ['hepatobiliary'], canonical: 'gastroenterology' },
  { keywords: ['hepatopancreatobiliary'], canonical: 'gastroenterology' },
  { keywords: ['dermatolog'], canonical: 'dermatology' },
  { keywords: ['cosmetolog'], canonical: 'dermatology' },
  { keywords: ['tricholog'], canonical: 'dermatology' },
  { keywords: ['pulmonolog'], canonical: 'pulmonology' },
  { keywords: ['respiratory'], canonical: 'pulmonology' },
  { keywords: ['chest', 'medicine'], canonical: 'pulmonology' },
  { keywords: ['tuberculosis'], canonical: 'pulmonology' },
  { keywords: ['endocrinolog'], canonical: 'endocrinology' },
  { keywords: ['diabetolog'], canonical: 'endocrinology' },
  { keywords: ['diabetes'], canonical: 'endocrinology' },
  { keywords: ['otolaryngolog'], canonical: 'ent' },
  { keywords: ['otorhinolaryngolog'], canonical: 'ent' },
  { keywords: ['psychiatr'], canonical: 'psychiatry' },
  { keywords: ['psycholog'], canonical: 'psychiatry' },
  { keywords: ['psychotherap'], canonical: 'psychiatry' },
  { keywords: ['urology'], canonical: 'urology' },
  { keywords: ['urologist'], canonical: 'urology' },
  { keywords: ['uro', 'surgery'], canonical: 'urology' },
  { keywords: ['endourology'], canonical: 'urology' },
  { keywords: ['plastic', 'surgery'], canonical: 'plastic surgery' },
  { keywords: ['cosmetic', 'surgery'], canonical: 'plastic surgery' },
  { keywords: ['reconstructive'], canonical: 'plastic surgery' },
  { keywords: ['burn'], canonical: 'plastic surgery' },
  { keywords: ['anesthesiolog'], canonical: 'anesthesiology' },
  { keywords: ['anaesthesiolog'], canonical: 'anesthesiology' },
  { keywords: ['anaesthesia'], canonical: 'anesthesiology' },
  { keywords: ['anesthesia'], canonical: 'anesthesiology' },
  { keywords: ['critical', 'care'], canonical: 'critical care' },
  { keywords: ['intensive', 'care'], canonical: 'critical care' },
  { keywords: ['intensivist'], canonical: 'critical care' },
  { keywords: ['emergency'], canonical: 'emergency medicine' },
  { keywords: ['accident'], canonical: 'emergency medicine' },
  { keywords: ['trauma', 'care'], canonical: 'emergency medicine' },
  { keywords: ['patholog'], canonical: 'pathology' },
  { keywords: ['microbiolog'], canonical: 'pathology' },
  { keywords: ['histopatholog'], canonical: 'pathology' },
  { keywords: ['cytolog'], canonical: 'pathology' },
  { keywords: ['radiolog'], canonical: 'radiology' },
  { keywords: ['sonograph'], canonical: 'radiology' },
  { keywords: ['dental'], canonical: 'dental' },
  { keywords: ['dentist'], canonical: 'dental' },
  { keywords: ['orthodontic'], canonical: 'dental' },
  { keywords: ['endodontic'], canonical: 'dental' },
  { keywords: ['periodontic'], canonical: 'dental' },
  { keywords: ['prosthodontic'], canonical: 'dental' },
  { keywords: ['pedodontic'], canonical: 'dental' },
  { keywords: ['maxillofacial'], canonical: 'dental' },
  { keywords: ['physiotherap'], canonical: 'physiotherapy' },
  { keywords: ['physical', 'medicine'], canonical: 'physiotherapy' },
  { keywords: ['rehabilitat'], canonical: 'physiotherapy' },
  { keywords: ['laborator'], canonical: 'laboratory' },
  { keywords: ['bariatric'], canonical: 'general surgery' },
  { keywords: ['laparoscop'], canonical: 'general surgery' },
  { keywords: ['vascular', 'surgery'], canonical: 'general surgery' },
  { keywords: ['transplant', 'surgery'], canonical: 'general surgery' },
  { keywords: ['general', 'surgery'], canonical: 'general surgery' },
  { keywords: ['internal', 'medicine'], canonical: 'general medicine' },
  { keywords: ['family', 'medicine'], canonical: 'general medicine' },
  { keywords: ['rheumatolog'], canonical: 'general medicine' },
  { keywords: ['immunolog'], canonical: 'general medicine' },
  { keywords: ['infectious'], canonical: 'general medicine' },
];

// ---------------------------------------------------------------------------
// Facility type expectations
// ---------------------------------------------------------------------------

export interface FacilityTypeExpectation {
  max_reasonable_specialties: number;
  max_reasonable_departments: number;
  expects_ot: boolean;
  expects_icu: boolean;
  /** Minimum beds to expect ICU at this type */
  icu_bed_threshold?: number;
  expects_emergency: boolean;
  min_expected_doctors: number;
}

export const FACILITY_TYPE_EXPECTATIONS: Record<string, FacilityTypeExpectation> = {
  Hospital: {
    max_reasonable_specialties: 30,
    max_reasonable_departments: 25,
    expects_ot: true,
    expects_icu: true,
    icu_bed_threshold: 50,
    expects_emergency: true,
    min_expected_doctors: 5,
  },
  'Multi-Specialty Hospital': {
    max_reasonable_specialties: 35,
    max_reasonable_departments: 30,
    expects_ot: true,
    expects_icu: true,
    icu_bed_threshold: 30,
    expects_emergency: true,
    min_expected_doctors: 10,
  },
  'Super-Specialty Hospital': {
    max_reasonable_specialties: 40,
    max_reasonable_departments: 35,
    expects_ot: true,
    expects_icu: true,
    icu_bed_threshold: 20,
    expects_emergency: true,
    min_expected_doctors: 15,
  },
  Clinic: {
    max_reasonable_specialties: 5,
    max_reasonable_departments: 3,
    expects_ot: false,
    expects_icu: false,
    expects_emergency: false,
    min_expected_doctors: 1,
  },
  Polyclinic: {
    max_reasonable_specialties: 10,
    max_reasonable_departments: 8,
    expects_ot: false,
    expects_icu: false,
    expects_emergency: false,
    min_expected_doctors: 3,
  },
  'Nursing Home': {
    max_reasonable_specialties: 10,
    max_reasonable_departments: 8,
    expects_ot: true,
    expects_icu: false,
    expects_emergency: false,
    min_expected_doctors: 2,
  },
  'Diagnostic Center': {
    max_reasonable_specialties: 5,
    max_reasonable_departments: 5,
    expects_ot: false,
    expects_icu: false,
    expects_emergency: false,
    min_expected_doctors: 2,
  },
  'Maternity Home': {
    max_reasonable_specialties: 5,
    max_reasonable_departments: 5,
    expects_ot: true,
    expects_icu: false,
    expects_emergency: false,
    min_expected_doctors: 2,
  },
  'Eye Hospital': {
    max_reasonable_specialties: 5,
    max_reasonable_departments: 5,
    expects_ot: true,
    expects_icu: false,
    expects_emergency: false,
    min_expected_doctors: 2,
  },
  'Dental Clinic': {
    max_reasonable_specialties: 3,
    max_reasonable_departments: 2,
    expects_ot: false,
    expects_icu: false,
    expects_emergency: false,
    min_expected_doctors: 1,
  },
  'Ayurveda Hospital': {
    max_reasonable_specialties: 8,
    max_reasonable_departments: 6,
    expects_ot: false,
    expects_icu: false,
    expects_emergency: false,
    min_expected_doctors: 2,
  },
  'Primary Health Center': {
    max_reasonable_specialties: 3,
    max_reasonable_departments: 3,
    expects_ot: false,
    expects_icu: false,
    expects_emergency: true,
    min_expected_doctors: 1,
  },
  'Community Health Center': {
    max_reasonable_specialties: 8,
    max_reasonable_departments: 6,
    expects_ot: true,
    expects_icu: false,
    expects_emergency: true,
    min_expected_doctors: 4,
  },
  'District Hospital': {
    max_reasonable_specialties: 20,
    max_reasonable_departments: 15,
    expects_ot: true,
    expects_icu: true,
    icu_bed_threshold: 30,
    expects_emergency: true,
    min_expected_doctors: 10,
  },
};

// ---------------------------------------------------------------------------
// Accreditation keywords
// ---------------------------------------------------------------------------

export const ACCREDITATION_KEYWORDS: string[] = [
  'NABH',
  'ISO',
  'JCI',
  'NABL',
  'QCI',
  'ISO 9001',
  'ISO 14001',
  'NQAS',
  'Kayakalp',
];

// ---------------------------------------------------------------------------
// Important fields for completeness scoring
// ---------------------------------------------------------------------------

export const IMPORTANT_FIELDS: string[] = [
  'facility_name',
  'facility_type',
  'state',
  'district',
  'pincode',
  'address',
  'latitude',
  'longitude',
  'num_doctors',
  'num_beds',
  'specialties',
  'equipment',
  'procedures',
  'departments',
  'ownership',
  'emergency_services',
  'website',
  'last_updated',
  'capabilities_text',
];
