// Auto-generated by AppKit - DO NOT EDIT
// Generated from serving endpoint OpenAPI schemas
import "@databricks/appkit";
import "@databricks/appkit-ui/react";

declare module "@databricks/appkit" {
  interface ServingEndpointRegistry {
    default: {
      request: Record<string, unknown>;
      response: unknown;
      chunk: unknown;
    };
  }
}

declare module "@databricks/appkit-ui/react" {
  interface ServingEndpointRegistry {
    default: {
      request: Record<string, unknown>;
      response: unknown;
      chunk: unknown;
    };
  }
}
